---
AWSTemplateFormatVersion: 2010-09-09


Parameters:
  AppEnv:
    Type: String
    Default: dev

  AppName:
    Type: String
    Default: sample


Resources:
  NginxRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Sub ${AppEnv}-${AppName}-nginx

  ApiRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Sub ${AppEnv}-${AppName}-api
